version: '3.5'
services:
  db:
      image: postgres:latest
      container_name: db
      environment:
        POSTGRES_DB: nestjs_drizzle  
        POSTGRES_USER: postgres   
        POSTGRES_PASSWORD: 123456 
      ports:
        - "5432:5432"
      volumes:
        - ./pg_data/:/var/lib/postgresql/data
      networks:
        - nest

networks:
    nest: